# Generated by Django 5.0.13 on 2025-07-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='quantiity',
            new_name='quantity',
        ),
    ]
